version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    steps:
      - checkout
      - run:
          name: Install packages
          command: sudo rm -rf /var/lib/apt/lists/* && sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
            name: Install AWS CLI
            command: |
                cd .circleci
                chmod +x awsinstall.sh
                ./awsinstall.sh
      - run: 
            name: Install dependencies
            command: mvn dependency:go-offline
      - run:
          name: Run Unit Tests
          command: mvn package
      - run:
          name: Build Artifacts
          command: |
            pwd
            ls -al
            mvn clean install
            cd target/
            ls -al
            echo "path check"
            pwd
            cd ../../..
            echo "After check"
            pwd
      - run:
          name: Zip Artifacts
          command: |
            mkdir -p artifact
            cd artifact
            ls -al
            touch 777 output.txt
      - run:
           name: Upload Artifact to S3 Bucket
           command: |
             aws --version
             pwd
             export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
             export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
             export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
             aws s3 cp /home/circleci/project/target/EmailTrigger.jar s3://${BUCKET_NAME} --region us-east-1
      - run:
          name: Update Lambda Function
          command: |
            aws lambda update-function-code --function-name  ${LAMBDA_NAME}  --s3-bucket ${BUCKET_NAME} --s3-key EmailTrigger.jar --region us-east-1 > output.txt
            echo "Lamda Updated"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master